services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /mnt/main_drive/jellyfiles/config:/config # Set to your config location
      - /mnt/main_drive/jellyfiles/cache:/cache
      - type: bind
        source: /mnt/main_drive/jellyfiles/media # Set to your media location, where your music is
        target: /media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
